### ISSUE TITLE
Error appearing in "train_network" level (ResourceExhaustedError >> get smaller images or a larger GPU, or turn already running net off...)

### ISSUE THREAD

**Issue by saritma** [DeepLabCut/DeepLabCut#133]
**Your Operating system and DeepLabCut version**
windows 10, DLC version2, conda environment, using jupyter notebook and GPU

**Describe the problem**
I reached the level of training the data with the file "demo with your own data", and I get an error. tried to use different sizes of display iters and save iters:

Config:
{'all_joints': [[0], [1]],
 'all_joints_names': ['snout', 'eye'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_try26Nov26\\try26_Sarit95shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'c:\\users\\sarit\\anaconda3\\envs\\saritenv\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1000,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_try26Nov26\\Documentation_data-try26_95shuffle1.pickle',
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 2,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\Sarit\\Desktop\\try26.11\\try26-Sarit-2018-11-26',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\Sarit\\Desktop\\try26.11\\try26-Sarit-2018-11-26\\dlc-models\\iteration-0\\try26Nov26-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Config:
{'all_joints': [[0], [1]],
 'all_joints_names': ['snout', 'eye'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_try26Nov26\\try26_Sarit95shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'c:\\users\\sarit\\anaconda3\\envs\\saritenv\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1000,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_try26Nov26\\Documentation_data-try26_95shuffle1.pickle',
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 2,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\Sarit\\Desktop\\try26.11\\try26-Sarit-2018-11-26',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\Sarit\\Desktop\\try26.11\\try26-Sarit-2018-11-26\\dlc-models\\iteration-0\\try26Nov26-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Config:
{'all_joints': [[0], [1]],
 'all_joints_names': ['snout', 'eye'],
 'batch_size': 1,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_try26Nov26\\try26_Sarit95shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': 'c:\\users\\sarit\\anaconda3\\envs\\saritenv\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1000,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_try26Nov26\\Documentation_data-try26_95shuffle1.pickle',
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 2,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': 'C:\\Users\\Sarit\\Desktop\\try26.11\\try26-Sarit-2018-11-26',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': 'C:\\Users\\Sarit\\Desktop\\try26.11\\try26-Sarit-2018-11-26\\dlc-models\\iteration-0\\try26Nov26-trainset95shuffle1\\train\\snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
INFO:tensorflow:Restoring parameters from c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
Restoring parameters from c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
Restoring parameters from c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
Restoring parameters from c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
Training parameter:
{'stride': 8.0, 'weigh_part_predictions': False, 'weigh_negatives': False, 'fg_fraction': 0.25, 'weigh_only_present_joints': False, 'mean_pixel': [123.68, 116.779, 103.939], 'shuffle': True, 'snapshot_prefix': 'C:\\Users\\Sarit\\Desktop\\try26.11\\try26-Sarit-2018-11-26\\dlc-models\\iteration-0\\try26Nov26-trainset95shuffle1\\train\\snapshot', 'log_dir': 'log', 'global_scale': 0.8, 'location_refinement': True, 'locref_stdev': 7.2801, 'locref_loss_weight': 0.05, 'locref_huber_loss': True, 'optimizer': 'sgd', 'intermediate_supervision': False, 'intermediate_supervision_layer': 12, 'regularize': False, 'weight_decay': 0.0001, 'mirror': False, 'crop_pad': 0, 'scoremap_dir': 'test', 'dataset_type': 'default', 'use_gt_segm': False, 'batch_size': 1, 'video': False, 'video_batch': False, 'crop': True, 'cropratio': 0.4, 'minsize': 100, 'leftwidth': 400, 'rightwidth': 400, 'topheight': 400, 'bottomheight': 400, 'all_joints': [[0], [1]], 'all_joints_names': ['snout', 'eye'], 'dataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_try26Nov26\\try26_Sarit95shuffle1.mat', 'display_iters': 1000, 'init_weights': 'c:\\users\\sarit\\anaconda3\\envs\\saritenv\\lib\\site-packages\\deeplabcut\\pose_estimation_tensorflow\\models\\pretrained\\resnet_v1_50.ckpt', 'max_input_size': 1000, 'metadataset': 'training-datasets\\iteration-0\\UnaugmentedDataSet_try26Nov26\\Documentation_data-try26_95shuffle1.pickle', 'multi_step': [[0.005, 10000], [0.02, 430000], [0.002, 730000], [0.001, 1030000]], 'net_type': 'resnet_50', 'num_joints': 2, 'pos_dist_thresh': 17, 'project_path': 'C:\\Users\\Sarit\\Desktop\\try26.11\\try26-Sarit-2018-11-26', 'save_iters': 50000, 'scale_jitter_lo': 0.5, 'scale_jitter_up': 1.25}
Starting training....
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1321     try:
-> 1322       return fn(*args)
   1323     except errors.OpError as e:

c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\client\session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1306       return self._call_tf_sessionrun(
-> 1307           options, feed_dict, fetch_list, target_list, run_metadata)
   1308 

c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\client\session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1408           self._session, options, feed_dict, fetch_list, target_list,
-> 1409           run_metadata)
   1410     else:

ResourceExhaustedError: OOM when allocating tensor with shape[1,2048,50,62] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: resnet_v1_50/block4/unit_3/bottleneck_v1/conv3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Relu, resnet_v1_50/block4/unit_3/bottleneck_v1/conv3/weights/read/_1247)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: pose/part_pred/block4/stack/_1347 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1430_pose/part_pred/block4/stack", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:

ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-9-9519d82efecc> in <module>()
----> 1 deeplabcut.train_network(path_config_file)

c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py in train_network(config, shuffle, trainingsetindex, gputouse, max_snapshots_to_keep, autotune, displayiters, saveiters, maxiters)
     79           train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep) #pass on path and file name for pose_cfg.yaml!
     80       except BaseException as e:
---> 81           raise e
     82       finally:
     83           os.chdir(str(start_path))

c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py in train_network(config, shuffle, trainingsetindex, gputouse, max_snapshots_to_keep, autotune, displayiters, saveiters, maxiters)
     77         os.environ['CUDA_VISIBLE_DEVICES'] = str(gputouse)
     78       try:
---> 79           train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep) #pass on path and file name for pose_cfg.yaml!
     80       except BaseException as e:
     81           raise e

c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py in train(config_yaml, displayiters, saveiters, maxiters, max_to_keep)
    140         current_lr = lr_gen.get_lr(it)
    141         [_, loss_val, summary] = sess.run([train_op, total_loss, merged_summaries],
--> 142                                           feed_dict={learning_rate: current_lr})
    143         cum_loss += loss_val
    144         train_writer.add_summary(summary, it)

c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)
    898     try:
    899       result = self._run(None, fetches, feed_dict, options_ptr,
--> 900                          run_metadata_ptr)
    901       if run_metadata:
    902         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1133     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1134       results = self._do_run(handle, final_targets, final_fetches,
-> 1135                              feed_dict_tensor, options, run_metadata)
   1136     else:
   1137       results = []

c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\client\session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1314     if handle is None:
   1315       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1316                            run_metadata)
   1317     else:
   1318       return self._do_call(_prun_fn, handle, feeds, fetches)

c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\client\session.py in _do_call(self, fn, *args)
   1333         except KeyError:
   1334           pass
-> 1335       raise type(e)(node_def, op, message)
   1336 
   1337   def _extend_graph(self):

ResourceExhaustedError: OOM when allocating tensor with shape[1,2048,50,62] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: resnet_v1_50/block4/unit_3/bottleneck_v1/conv3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Relu, resnet_v1_50/block4/unit_3/bottleneck_v1/conv3/weights/read/_1247)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: pose/part_pred/block4/stack/_1347 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1430_pose/part_pred/block4/stack", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

Caused by op 'resnet_v1_50/block4/unit_3/bottleneck_v1/conv3/Conv2D', defined at:
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\asyncio\base_events.py", line 427, in run_forever
    self._run_once()
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\asyncio\base_events.py", line 1440, in _run_once
    handle._run()
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tornado\gen.py", line 1233, in inner
    self.run()
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\IPython\core\interactiveshell.py", line 2683, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\IPython\core\interactiveshell.py", line 2793, in run_ast_nodes
    if self.run_code(code, result):
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\IPython\core\interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-9519d82efecc>", line 1, in <module>
    deeplabcut.train_network(path_config_file)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\training.py", line 79, in train_network
    train(str(poseconfigfile),displayiters,saveiters,maxiters,max_to_keep=max_snapshots_to_keep) #pass on path and file name for pose_cfg.yaml!
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\train.py", line 89, in train
    losses = pose_net(cfg).train(batch)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 100, in train
    heads = self.get_net(batch[Batch.inputs])
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 89, in get_net
    net, end_points = self.extract_features(inputs)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\deeplabcut\pose_estimation_tensorflow\nnet\pose_net.py", line 62, in extract_features
    global_pool=False, output_stride=16,is_training=False)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_v1.py", line 274, in resnet_v1_50
    scope=scope)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_v1.py", line 207, in resnet_v1
    net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_utils.py", line 211, in stack_blocks_dense
    net = block.unit_fn(net, rate=rate, **dict(unit, stride=1))
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\contrib\slim\python\slim\nets\resnet_v1.py", line 121, in bottleneck
    residual, depth, [1, 1], stride=1, activation_fn=None, scope='conv3')
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1049, in convolution
    outputs = layer.apply(inputs)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\layers\base.py", line 828, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\layers\base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\layers\convolutional.py", line 168, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 868, in __call__
    return self.conv_op(inp, filter)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 520, in __call__
    return self.call(inp, filter)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 204, in __call__
    name=self.name)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 1042, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\framework\ops.py", line 3392, in create_op
    op_def=op_def)
  File "c:\users\sarit\anaconda3\envs\saritenv\lib\site-packages\tensorflow\python\framework\ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,2048,50,62] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: resnet_v1_50/block4/unit_3/bottleneck_v1/conv3/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Relu, resnet_v1_50/block4/unit_3/bottleneck_v1/conv3/weights/read/_1247)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: pose/part_pred/block4/stack/_1347 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1430_pose/part_pred/block4/stack", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

I could't find what is the problem. Please help.

**Comment by MMathisLab** [comment]
Seems your image is too large for your gpu to handle... does the demo on our data work for you? 

ResourceExhaustedError: OOM when allocating tensor with shape[1,2048,50,62] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

**Comment by saritma** [comment]
I tried the demo last week and it worked.
Tried it today too and the kernel died.

**Comment by MMathisLab** [comment]
Yeah, So it’s not our code, it is either you have multiple tensorflow sessions running or your GPU Is not large enough for your image size. I would check your card by running nvidia-smi in the terminal and seeing if it’s being used. Hope that helps!

**Comment by vladscript** [comment]
Hi, I have a similar problem:
(**Ubuntu 18 with  GPU 1050 ti, conda environment and docker DLCv2**)

I crashed my PC training a model becasue I naively tried to train in 2 DLC sessions (now I got it) using docker. So the training did not finish but I got a snapshot , so when I try try to train or analyze a video from the snapshot I got that error: **ResourceExhaustedError** with the same kind of data (same camera, size, etc).

So, I thought that some memory can't be unfreed but I tried a demo and it worked.

Any other advice than resizing images and videos, diminishing batch size (maybe)
**why did it work once (to get the snapshot) and now I can't retrain?**

**Comment by MMathisLab** [comment]
how large are your video frames? a 1050 have very little memory capacity, unfortunately. 

also, when you check NVIDIA-SMI is your GPU free? it should have no processes that say python. 

if a python process is there,  kill the process ID, i.e. "kill 1094"

![image](https://user-images.githubusercontent.com/28102185/66336801-d17c3100-e90b-11e9-8ca6-a3c20714e92c.png)

**Comment by vladscript** [comment]
Video frames are 1025 x 831, (I even tried these images using CPU so I thought it just would've been slow) and to analyze are about 0.5 GB

nvidia-smi's output shows a python process when it's training and when I got that error I only can exit docker by killing it (exit() does not work):

![Screenshot from 2019-10-07 13-33-58](https://user-images.githubusercontent.com/7875020/66338943-befff880-e907-11e9-8e1e-7122dae2c809.png)

**Comment by MMathisLab** [comment]
seems you are tapping out your GPU (3847/4036 MiB) - we have it set so the limit is 80% as to not crash your PC, unless you overwrote this. 

I would downsample your frames. You can use the new function ``deeplabcut.DownSampleVideo``
