### ISSUE TITLE
`RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1.`

### ISSUE THREAD

**Issue by felipearrudamoura** [DeepLabCut/DeepLabCut#1942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After analyzing the videos, I tried to perform the reId transform, but the following error occurred:

Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'ball'],
 'batch_size': 1,
 'crop_pad': 0,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_UFALAug5/UFAL_CRB18062295shuffle1.pickle',
 'dataset_type': 'multi-animal-imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_smooth': False,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'minconfidence': 0.01,
 'mirror': False,
 'multi_stage': True,
 'net_type': 'resnet_50',
 'nmsradius': 5.0,
 'num_idchannel': 11,
 'num_joints': 4,
 'num_limbs': 3,
 'optimizer': 'sgd',
 'paf_best': [0, 1, 2],
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_graph': [[0, 1], [0, 2], [1, 2]],
 'partaffinityfield_predict': True,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'sigma': 1,
 'snapshot_prefix': '/home/preto/DLC/UFAL/UFAL-CRB180622-2022-08-05/dlc-models/iteration-0/UFALAug5-trainset95shuffle1/test/snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Using snapshot-200000 for model /home/preto/DLC/UFAL/UFAL-CRB180622-2022-08-05/dlc-models/iteration-0/UFALAug5-trainset95shuffle1
/home/preto/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer._call_` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Activating extracting of PAFs
2022-08-11 10:52:27.367998: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-11 10:52:27.368198: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-11 10:52:27.368297: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-11 10:52:27.368432: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-11 10:52:27.368530: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-11 10:52:27.368592: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22300 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6
Starting to analyze %  /home/preto/DLC/UFAL/CRBxAzurra/Cameras_Arquibancada/Cam_03_02.avi
Loading  /home/preto/DLC/UFAL/CRBxAzurra/Cameras_Arquibancada/Cam_03_02.avi
Duration of video [s]:  2129.13 , recorded with  30.0 fps!
Overall # of frames:  63874  found with (before cropping) frame dimensions:  2560 1440
Starting to extract posture
100%|███████████████████████████████████████████████████████████████| 63874/63874 [02:22<00:00, 448.35it/s]
Starting to analyze %  /home/preto/DLC/UFAL/CRBxAzurra/Cameras_Arquibancada/Cam_04_02.avi
Loading  /home/preto/DLC/UFAL/CRBxAzurra/Cameras_Arquibancada/Cam_04_02.avi
Duration of video [s]:  2129.13 , recorded with  30.0 fps!
Overall # of frames:  63874  found with (before cropping) frame dimensions:  2560 1440
Starting to extract posture
100%|███████████████████████████████████████████████████████████████| 63874/63874 [02:23<00:00, 445.83it/s]
/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/tracking_utils/preprocessing.py:54: RuntimeWarning: Mean of empty slice
  match_id = np.argmin(np.nanmean(diff, axis=(1, 2)))
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
start training
Traceback (most recent call last):
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/gui/transformerID.py", line 195, in run_transformer_reID
    deeplabcut.transformer_reID(
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/apis.py", line 120, in transformer_reID
    deeplabcut.pose_tracking_pytorch.train_tracking_transformer(
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/train_dlctransreid.py", line 108, in train_tracking_transformer
    do_dlc_train(
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/processor/processor.py", line 109, in do_dlc_train
    anchor_feat = model(anchor)
  File "/home/preto/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/model/make_model.py", line 37, in forward
    global_feat = self.base(x)
  File "/home/preto/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/model/backbones/vit_pytorch.py", line 301, in forward
    x = self.forward_features(x)
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/model/backbones/vit_pytorch.py", line 275, in forward_features
    x = self.kpt_embed(x)
  File "/home/preto/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/model/backbones/vit_pytorch.py", line 185, in forward
    x = self.proj(x)
  File "/home/preto/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/preto/.local/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

### Operating System

Ubuntu 20.04.4 LTS

### DeepLabCut version

2.2.1.1

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['bodypart1', 'bodypart2', 'bodypart3', 'ball'],
 'batch_size': 1,
 'crop_pad': 0,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_UFALAug5/UFAL_CRB18062295shuffle1.pickle',
 'dataset_type': 'multi-animal-imgaug',
 'deterministic': False,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 1.0,
 'locref_smooth': False,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'mean_pixel': [123.68, 116.779, 103.939],
 'minconfidence': 0.01,
 'mirror': False,
 'multi_stage': True,
 'net_type': 'resnet_50',
 'nmsradius': 5.0,
 'num_idchannel': 11,
 'num_joints': 4,
 'num_limbs': 3,
 'optimizer': 'sgd',
 'paf_best': [0, 1, 2],
 'pairwise_huber_loss': True,
 'pairwise_predict': False,
 'partaffinityfield_graph': [[0, 1], [0, 2], [1, 2]],
 'partaffinityfield_predict': True,
 'regularize': False,
 'scoremap_dir': 'test',
 'shuffle': True,
 'sigma': 1,
 'snapshot_prefix': '/home/preto/DLC/UFAL/UFAL-CRB180622-2022-08-05/dlc-models/iteration-0/UFALAug5-trainset95shuffle1/test/snapshot',
 'stride': 8.0,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}
Using snapshot-200000 for model /home/preto/DLC/UFAL/UFAL-CRB180622-2022-08-05/dlc-models/iteration-0/UFALAug5-trainset95shuffle1
/home/preto/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer_v1.py:1694: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer._call_` method instead.
  warnings.warn('`layer.apply` is deprecated and '
Activating extracting of PAFs
2022-08-11 10:52:27.367998: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-11 10:52:27.368198: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-11 10:52:27.368297: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-11 10:52:27.368432: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-11 10:52:27.368530: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-08-11 10:52:27.368592: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 22300 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6
Starting to analyze %  /home/preto/DLC/UFAL/CRBxAzurra/Cameras_Arquibancada/Cam_03_02.avi
Loading  /home/preto/DLC/UFAL/CRBxAzurra/Cameras_Arquibancada/Cam_03_02.avi
Duration of video [s]:  2129.13 , recorded with  30.0 fps!
Overall # of frames:  63874  found with (before cropping) frame dimensions:  2560 1440
Starting to extract posture
100%|███████████████████████████████████████████████████████████████| 63874/63874 [02:22<00:00, 448.35it/s]
Starting to analyze %  /home/preto/DLC/UFAL/CRBxAzurra/Cameras_Arquibancada/Cam_04_02.avi
Loading  /home/preto/DLC/UFAL/CRBxAzurra/Cameras_Arquibancada/Cam_04_02.avi
Duration of video [s]:  2129.13 , recorded with  30.0 fps!
Overall # of frames:  63874  found with (before cropping) frame dimensions:  2560 1440
Starting to extract posture
100%|███████████████████████████████████████████████████████████████| 63874/63874 [02:23<00:00, 445.83it/s]
/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/tracking_utils/preprocessing.py:54: RuntimeWarning: Mean of empty slice
  match_id = np.argmin(np.nanmean(diff, axis=(1, 2)))
If the tracking is not satisfactory for some videos, consider expanding the training set. You can use the function 'extract_outlier_frames' to extract a few representative outlier frames.
start training
Traceback (most recent call last):
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/gui/transformerID.py", line 195, in run_transformer_reID
    deeplabcut.transformer_reID(
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/apis.py", line 120, in transformer_reID
    deeplabcut.pose_tracking_pytorch.train_tracking_transformer(
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/train_dlctransreid.py", line 108, in train_tracking_transformer
    do_dlc_train(
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/processor/processor.py", line 109, in do_dlc_train
    anchor_feat = model(anchor)
  File "/home/preto/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/model/make_model.py", line 37, in forward
    global_feat = self.base(x)
  File "/home/preto/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/model/backbones/vit_pytorch.py", line 301, in forward
    x = self.forward_features(x)
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/model/backbones/vit_pytorch.py", line 275, in forward_features
    x = self.kpt_embed(x)
  File "/home/preto/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/preto/.local/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/model/backbones/vit_pytorch.py", line 185, in forward
    x = self.proj(x)
  File "/home/preto/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/preto/.local/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
@felipearrudamoura your images are massive -- you would have needed to change a few things about training if you want to use this size; can you downsample? I imagine your NVIDIA GeForce RTX 3090 is not large enough for processing this video.

**Comment by yeshaokai** [comment]
Hello,
That error is usually a mismatch between pytorch version and cuda, as explained in this pytorch issue https://github.com/pytorch/pytorch/issues/31285

There are tables online that specify which CUDA version is compatible with which pytorch version. Can you check or post your CUDA/pytorch version?

**Comment by MMathisLab** [comment]
closed due to inactivity.

**Comment by hosein-cnn** [comment]
Hi, I am also facing this problem.
I just want to write simple Cuda C++ code.

I use the following :

1. Windows 10 , 19044(21H2)
2. Visual Studio 2019 or 2022
3. Nvidia GeForce GTX 960m , Maxwell , Capability 5.0
4. Cuda Toolkit 11.7 or 11.8 or 12.0

After I installed all the packages related to C++ on VS2019, I installed Cuda Toolkit.
When I run sample code , I get the following error :

- **No kernel image is available for execution on the device.**

I even ran Cuda 11.7, 11.8 and 12.0 on VS2019 and VS2022, But the error still exists.
I am facing this error for 20 days and I am really fed up. also **deviceQuery.exe** and **nvidia-smi** and **nvcc --version** runs fine.
I have also checked all the nvidia and other sites and my GPU has no problem with the Cuda version.
**What factors can cause this error ?**
**What could be the reasons for this error?**

_please help me out ,
thanks all._

**Comment by Zahra-Mazinani** [comment]
Hi,
I had your problem too.
this happens because of the torch version and Cuda.
I used this command to upgrade the torch version, which works for me.
pip3 install -U torch

**Comment by lalit-pivotchain** [comment]
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
