### ISSUE TITLE
tensorflow and libnvinfer_plugin.so.7 issue

### ISSUE THREAD

**Issue by DavidBarriere** [DeepLabCut/DeepLabCut#2454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description
```
2023-11-22 16:09:32.517102: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-22 16:09:32.648135: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-22 16:09:32.677864: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-22 16:09:33.263809: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-11-22 16:09:33.264035: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-11-22 16:09:33.264044: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
```

### Operating System

Linux x86_64

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### DeepLabCut version

'2.3.8'

### DeepLabCut mode

multi animal

### Device type

gpu

### Steps To Reproduce

1. in this env
2. in this config
3. I run python -m deeplabcut
4. see error
```
2023-11-22 16:14:20.913821: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-22 16:14:21.015691: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-22 16:14:21.038396: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-22 16:14:21.537966: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-11-22 16:14:21.538049: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-11-22 16:14:21.538055: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.3.8...
Starting GUI...
libGL error: MESA-LOADER: failed to open iris: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```

### Relevant log output

```shell
2023-11-22 16:14:20.913821: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-22 16:14:21.015691: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-22 16:14:21.038396: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-22 16:14:21.537966: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-11-22 16:14:21.538049: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-11-22 16:14:21.538055: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.3.8...
Starting GUI...
libGL error: MESA-LOADER: failed to open iris: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by KonradDanielewski** [comment]
Did you build the env yourself? Looks like it should be solved by: https://stackoverflow.com/a/74976131/12268374 but you may have additional issues aside from the tensorflow ones

**Comment by DavidBarriere** [comment]
I built it as recommended here.

I did :
```
(DLC) dbarriere@dbarriere-Precision-7560:$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOME}/anaconda3/lib/
(DLC) dbarriere@dbarriere-Precision-7560:$  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOME}/anaconda3/lib/python3.8/site-packages/tensorrt/
(DLC) dbarriere@dbarriere-Precision-7560:$  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOME}/anaconda3/envs/tf/lib
(DLC) dbarriere@dbarriere-Precision-7560:$  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOME}/anaconda3/envs/tf/lib/python3.8/site-packages/tensorrt/
```

I obtained : 
```
python -m deeplabcut
2023-11-22 17:33:51.820295: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-22 17:33:51.979454: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-22 17:33:52.012848: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-22 17:33:52.623377: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-11-22 17:33:52.623417: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-11-22 17:33:52.623431: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.3.8...
Starting GUI...
libGL error: MESA-LOADER: failed to open iris: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /lib/x86_64-linux-gnu/libLLVM-12.so.1: undefined symbol: ffi_type_sint32, version LIBFFI_BASE_7.0 (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```

**Comment by n-poulsen** [comment]
Hi @DavidBarriere, could you check out issue #2338? This was the same issue you're having now, and maybe it can be resolved in the same way

**Comment by DavidBarriere** [comment]
Okay thanks.
So, I uninstall both CUDA and NVIDIA but also deeplabcut to my machine to restart from scratch.
I carefully follow instruction from website and reinstall DLC in conda using DEEPLABCUT.yaml.
At the openning of DLC I still obtain error message : 
```
(DLC) dbarriere@dbarriere-Precision-7560:~/DeepLabCut/conda-environments$ python -m deeplabcut
2023-11-23 10:01:24.800712: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, **rebuild TensorFlow with the appropriate compiler flags (_what does it means?_).**
2023-11-23 10:01:24.961034: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-23 10:01:24.964656: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] **Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory**
2023-11-23 10:01:24.964683: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-11-23 10:01:24.983482: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] **Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered**
2023-11-23 10:01:25.538660: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] **Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory**
2023-11-23 10:01:25.538702: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] **Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory**
2023-11-23 10:01:25.538707: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.3.8...
Starting GUI...
```

**Comment by DavidBarriere** [comment]
here's what I get after napari --info:
```
napari: 0.4.18
Platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.6 LTS
Python: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32)  [GCC 12.3.0]
Qt: 6.3.1
PySide6: 
NumPy: 1.26.2
SciPy: 1.11.1
Dask: 2023.11.0
VisPy: 0.12.2
magicgui: 0.8.0
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.3

OpenGL:
  - GL version:  4.6 (Compatibility Profile) Mesa 21.2.6
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 5120x1440, scale 1.0

Settings path:
  - /home/dbarriere/.config/napari/DLC_77f2ec78b4e4d8aee33b16bec4d5936bb9393723/settings.yaml
Plugins:
  - napari: 0.4.18 (77 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-deeplabcut: 0.2.1.2 (16 contributions)
  - napari-svg: 0.1.10 (2 contributions)
```

**Comment by DavidBarriere** [comment]
But in my case the gui is working.

**Comment by n-poulsen** [comment]
Yes seems like now the issue is more with the tensorflow installation. Could you please let me know which versions of `tensorflow` and `cudnn` you have installed (you can just print the output of `pip list`)?

**Comment by DavidBarriere** [comment]
tenorflow

**Comment by DavidBarriere** [comment]
Thank you.
There is no cudnn installed. 
here the version for tensorflow :
```
tensorflow                    2.10.0
tensorflow-estimator          2.10.0
tensorflow-io-gcs-filesystem  0.34.0
tensorpack                    0.11
```

Here the complete list :
```
Package                       Version
----------------------------- ----------
absl-py                       2.0.0
alabaster                     0.7.13
anyio                         3.7.1
app-model                     0.2.2
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
asttokens                     2.2.1
astunparse                    1.6.3
async-lru                     2.0.3
attrs                         23.1.0
Babel                         2.12.1
backcall                      0.2.0
beautifulsoup4                4.12.2
bleach                        6.0.0
blosc2                        2.3.1
build                         1.0.3
cached-property               1.5.2
cachetools                    5.3.2
cachey                        0.2.1
certifi                       2023.11.17
cffi                          1.15.1
charset-normalizer            3.2.0
click                         8.1.7
cloudpickle                   3.0.0
colourmap                     1.1.14
comm                          0.1.3
contourpy                     1.2.0
cycler                        0.12.1
d3blocks                      1.3.0
d3graph                       2.4.6
dask                          2023.11.0
dask-image                    2023.8.1
debugpy                       1.6.7
decorator                     5.1.1
deeplabcut                    2.3.8
defusedxml                    0.7.1
dlclibrary                    0.0.4
docstring-parser              0.15
docutils                      0.17.1
elasticgraph                  0.2.0
entrypoints                   0.4
exceptiongroup                1.1.2
executing                     1.2.0
fastjsonschema                2.18.0
filelock                      3.13.1
filterpy                      1.4.5
flatbuffers                   23.5.26
fonttools                     4.45.1
fqdn                          1.5.1
freetype-py                   2.4.0
fsspec                        2023.10.0
gast                          0.4.0
google-auth                   2.23.4
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
grpcio                        1.59.3
h5py                          3.10.0
HeapDict                      1.0.1
hsluv                         5.0.4
huggingface-hub               0.19.4
idna                          3.4
imageio                       2.33.0
imageio-ffmpeg                0.4.9
imagesize                     1.4.1
imgaug                        0.4.0
importlib-metadata            6.8.0
importlib-resources           6.1.1
in-n-out                      0.1.9
ipykernel                     6.25.0
ipython                       8.14.0
ipython-genutils              0.2.0
ipywidgets                    8.0.7
ismember                      1.0.2
isoduration                   20.11.0
jedi                          0.18.2
Jinja2                        3.1.2
joblib                        1.3.1
json5                         0.9.14
jsonpointer                   2.4
jsonschema                    4.18.4
jsonschema-specifications     2023.7.1
jupyter                       1.0.0
jupyter_client                8.3.0
jupyter-console               6.6.3
jupyter_core                  5.3.1
jupyter-events                0.6.3
jupyter-lsp                   2.2.0
jupyter_server                2.7.0
jupyter_server_terminals      0.4.4
jupyterlab                    4.0.3
jupyterlab-pygments           0.2.2
jupyterlab_server             2.24.0
jupyterlab-widgets            3.0.8
keras                         2.10.0
Keras-Preprocessing           1.1.2
kiwisolver                    1.4.5
lazy_loader                   0.3
libclang                      16.0.6
llvmlite                      0.41.1
locket                        1.0.0
magicgui                      0.8.0
Markdown                      3.5.1
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib                    3.8.2
matplotlib-inline             0.1.6
mdurl                         0.1.2
mistune                       3.0.1
msgpack                       1.0.7
msgpack-numpy                 0.4.8
mypy-extensions               1.0.0
napari                        0.4.18
napari-console                0.0.9
napari-deeplabcut             0.2.1.2
napari-plugin-engine          0.2.0
napari-svg                    0.1.10
natsort                       8.4.0
nb-conda                      2.2.1
nb-conda-kernels              2.3.1
nbclassic                     1.0.0
nbclient                      0.8.0
nbconvert                     7.7.3
nbformat                      5.9.1
ndindex                       1.7
nest-asyncio                  1.5.6
networkx                      3.1
notebook                      6.1.5
notebook_shim                 0.2.3
npe2                          0.7.3
numba                         0.58.1
numexpr                       2.8.7
numpy                         1.26.2
numpydoc                      1.5.0
oauthlib                      3.2.2
opencv-python                 4.8.1.78
opencv-python-headless        4.8.1.78
opt-einsum                    3.3.0
overrides                     7.3.1
packaging                     23.1
pandas                        2.0.3
pandocfilters                 1.5.0
parso                         0.8.3
partd                         1.4.1
patsy                         0.5.3
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        10.1.0
PIMS                          0.6.1
Pint                          0.22
pip                           23.3.1
pkgutil_resolve_name          1.3.10
platformdirs                  3.9.1
pooch                         1.8.0
prometheus-client             0.17.1
prompt-toolkit                3.0.39
protobuf                      3.19.6
psutil                        5.9.5
psygnal                       0.9.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyasn1                        0.5.1
pyasn1-modules                0.3.0
pyconify                      0.1.6
pycparser                     2.21
pydantic                      1.10.13
Pygments                      2.15.1
PyOpenGL                      3.1.7
pyparsing                     3.1.1
pyproject_hooks               1.0.0
PySide6                       6.3.1
PySide6-Addons                6.3.1
PySide6-Essentials            6.3.1
python-dateutil               2.8.2
python-json-logger            2.0.7
python-louvain                0.16
pytz                          2023.3
PyYAML                        6.0.1
pyzmq                         25.1.0
QDarkStyle                    3.1
qtconsole                     5.4.3
QtPy                          2.4.1
referencing                   0.30.0
requests                      2.31.0
requests-oauthlib             1.3.1
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.7.0
rpds-py                       0.9.2
rsa                           4.9
ruamel.yaml                   0.18.5
ruamel.yaml.clib              0.2.8
scikit-image                  0.22.0
scikit-learn                  1.3.0
scipy                         1.11.1
Send2Trash                    1.8.2
setuptools                    68.2.2
shapely                       2.0.2
shiboken6                     6.3.1
six                           1.16.0
slicerator                    1.1.0
sniffio                       1.3.0
snowballstemmer               2.2.0
soupsieve                     2.4.1
Sphinx                        4.5.0
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
stack-data                    0.6.2
statsmodels                   0.14.0
superqt                       0.6.1
tables                        3.9.1
tabulate                      0.9.0
tensorboard                   2.10.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.10.0
tensorflow-estimator          2.10.0
tensorflow-io-gcs-filesystem  0.34.0
tensorpack                    0.11
termcolor                     2.3.0
terminado                     0.17.1
tf-slim                       1.1.0
threadpoolctl                 3.2.0
tifffile                      2023.9.26
tinycss2                      1.2.1
tomli                         2.0.1
tomli_w                       1.0.0
toolz                         0.12.0
torch                         1.12.0
tornado                       6.3.2
tqdm                          4.65.0
traitlets                     5.9.0
typer                         0.9.0
types-python-dateutil         2.8.19.14
typing_extensions             4.7.1
typing-utils                  0.1.0
tzdata                        2023.3
uri-template                  1.3.0
urllib3                       2.0.4
vispy                         0.12.2
wcwidth                       0.2.6
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.6.1
Werkzeug                      3.0.1
wheel                         0.41.3
widgetsnbextension            4.0.8
wrapt                         1.16.0
zipp                          3.16.2
```

**Comment by n-poulsen** [comment]
Seems to me that it's exactly the same problem as discussed here: [libGL error: failed to load drivers iris and swrast in Ubuntu 20.04](https://askubuntu.com/questions/1352158/libgl-error-failed-to-load-drivers-iris-and-swrast-in-ubuntu-20-04).

Could you try running one of the solutions offered? This seems like the most likely to succeed to me:
```
sudo apt-get install libgl1-mesa-dri
```

**Comment by Dylan-Trows** [comment]
I'm experiencing the same problem as above.  Is there any fix to this? Thank you.

## operating system
Linux x86_64
Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-167-generic x86_64)
## DeepLabCut version
dlc version 2.3.5
## DeepLabCut mode
single animal
## Device type
gpu: 2x NVIDIA GeForce RTX2080ti in sli



## steps to reproduce
docker pull deeplabcut/deeplabcut:2.3.5-core-cuda11.7.1-cudnn8-runtime-ubuntu20.04-latest
docker run -it --gpus all -v /data/dylan:/data deeplabcut/deeplabcut:2.3.5-core-cuda11.7.1-cudnn8-runtime-ubuntu20.04-latest
python3
import deeplabcut

## log output
2023-12-05 16:25:52.559393: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-05 16:25:53.211276: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-12-05 16:25:53.211330: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-12-05 16:25:53.211339: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

**Comment by jeylau** [comment]
@DavidBarriere @Dylan-Trows this is a warning I also see on my Linux machines, but it never prevented me from training/evaluating models with GPUs. You could run the test script with `python examples/testscript.py` to verify. Unless you plan to use TensorRT later on, I'd ignore that message.

**Comment by DavidBarriere** [comment]
@jeylau 
I previously run the testscript.py.
The training dataset has been successfully created nevertheless I am still worried about this :

(DLC) dbarriere@dbarriere-Precision-7560:~/DeepLabCut$ python examples/testscript.py
2023-12-08 13:20:05.562945: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-08 13:20:05.778626: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-08 13:20:05.826536: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-12-08 13:20:05.826552: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-12-08 13:20:05.858639: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-08 13:20:06.593722: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-12-08 13:20:06.593773: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-12-08 13:20:06.593778: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

This :
Traceback (most recent call last):
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 86, in load_and_enqueue
    sess.run(enqueue_op, feed_dict=food)
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 968, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1191, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1371, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1397, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.CancelledError: Graph execution error:

Detected at node 'fifo_queue_enqueue' defined at (most recent call last):
    File "/home/dbarriere/DeepLabCut/examples/testscript.py", line 311, in <module>
      deeplabcut.train_network(path_config_file, maxiters=N_ITER)
    File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 273, in train_network
      train(
    File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 172, in train
      batch, enqueue_op, placeholders = setup_preloading(batch_spec)
    File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 72, in setup_preloading
      enqueue_op = q.enqueue(placeholders_list)
Node: 'fifo_queue_enqueue'
Enqueue operation was cancelled
	 [[{{node fifo_queue_enqueue}}]]

Original stack trace for 'fifo_queue_enqueue':
  File "/home/dbarriere/DeepLabCut/examples/testscript.py", line 311, in <module>
    deeplabcut.train_network(path_config_file, maxiters=N_ITER)
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/training.py", line 273, in train_network
    train(
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 172, in train
    batch, enqueue_op, placeholders = setup_preloading(batch_spec)
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/deeplabcut/pose_estimation_tensorflow/core/train.py", line 72, in setup_preloading
    enqueue_op = q.enqueue(placeholders_list)
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/tensorflow/python/ops/data_flow_ops.py", line 346, in enqueue
    return gen_data_flow_ops.queue_enqueue_v2(
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 4063, in queue_enqueue_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 797, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/home/dbarriere/anaconda3/envs/DLC/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3800, in _create_op_internal
    ret = Operation(



This : 
2023-12-08 13:21:02.137236: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1934] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.



And this : 
1208 13:21:04 @develop.py:109] WRN [Deprecated] GaussianBlur(max_size=) will be deprecated after 01 sept.. Use size_range= instead!
[1208 13:21:04 @parallel.py:340] [MultiProcessRunnerZMQ] Will fork a dataflow more than one times. This assumes the datapoints are i.i.d.
[1208 13:21:04 @argtools.py:138] WRN Starting a process with 'fork' method is efficient but not safe and may cause deadlock or crash.Use 'forkserver' or 'spawn' method instead if you run into such issues.See https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods on how to set them.
[1208 13:21:04 @argtools.py:138] WRN "import prctl" failed! Install python-prctl so that processes can be cleaned with guarantee.


And GPU mode is still unworking.
But I can use CPU

**Comment by jeylau** [comment]
Aw sorry, I missed `Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory` in later posts. This one is indeed problematic. Have you tried to run `conda install cudatoolkit`?

**Comment by DavidBarriere** [comment]
It is installed now but the error message stay.
But maybe the problem is : 

sudo find / -name 'libcudart.so.11.0'
/home/dbarriere/anaconda3/lib/libcudart.so.11.0
/home/dbarriere/anaconda3/pkgs/cudatoolkit-11.8.0-h6a678d5_0/lib/libcudart.so.11.0

Does it normal to get it twice ?

**Comment by Andres9713** [comment]
I saw each of the errors above at some point, I solved it as described here: https://github.com/DeepLabCut/DeepLabCut/issues/2338#issuecomment-1818225631 - I saw this thread because I was looking up my old comment for new install (and it still works). My method is clunky though, both in time and for the fact that it is vulnerable to breaking during updates - so, not great. I'm hoping that perhaps I, or someone else, can streamline my solutions to something more elegant but so far those steps are what's worked for me on what look to be pretty related issues. Your mileage may vary.
