### ISSUE TITLE
DLC 3.0: Minimal GPU usage

### ISSUE THREAD

**Issue by roaldarbol** [DeepLabCut/DeepLabCut#2639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I'm starting out with some tracking again, now with the new PyTorch backend. I'm analysing some massive videos, 2 hours at 60fps and dimensions `w=1280, h=720`. Currently I'm getting just over 7fps when I'm analysing videos. The issue is not that PyTorch is not registering the GPU - I had that issue (was getting 1.3fps before when `torch.cuda.is_available()` returned `False`, now it returns `True`), but even with the GPU being accessible, it's not really being used much, sitting at about 10%, and the Python thread running DLC is using less than 1% of that.

### Operating System

Windows 10

### DeepLabCut version

DLC 3.0.0rc1

### DeepLabCut mode

single animal

### Device type

Nvidia Quadro M5000, 8GB

### Steps To Reproduce

1. Install DLC 3.0.0rc1 as per the installation instructions for Windows.
2. Start tracking videos
3. Watch the GPU usage in the Task Manager

### Anything else?

Here see the total GPU usage:
![gpu-usage](https://github.com/DeepLabCut/DeepLabCut/assets/25629697/6de32f55-ea7c-4dba-b9f3-059e8e041007)

Here, see that the Python process uses less than 1% GPU:
![gpu-usage2](https://github.com/DeepLabCut/DeepLabCut/assets/25629697/2a2987a6-21c2-4f02-9b65-61ab8766aebc)

Again, this time from `nvidia-smi`, the memory usage is less than 10% (812Mb/8192Mb):
![nvidia-smi](https://github.com/DeepLabCut/DeepLabCut/assets/25629697/6eb6d8c5-7d62-416d-9624-bdc57aca5739)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by roaldarbol** [comment]
EDIT: Apologies for the tiny images, dunno whay they aren't any bigger... Hopefully you can somehwat make out what they say!

**Comment by roaldarbol** [comment]
For reference, the GPU is heavily engaged during training:
![training-usage2](https://github.com/DeepLabCut/DeepLabCut/assets/25629697/fb6fff2b-eec6-4807-bf22-d06b43ce3b6d)
![training-usage](https://github.com/DeepLabCut/DeepLabCut/assets/25629697/87310067-29a4-492d-a622-84bd62bf3a3a)

**Comment by roaldarbol** [comment]
I've also followed the new installation steps to install the stable TF version. Currently I'm training a ResNet50 network on the same images, and the GPU process is running at ~20%. Will update once I can begin analysing videos.

**Comment by n-poulsen** [comment]
@roaldarbol thanks for working on this! I'll take a look and get back to you

**Comment by roaldarbol** [comment]
Sounds good, thanks @n-poulsen! Let me know whenever whatever you need from my side, can also run some tests if needed. :-)

**Comment by chz31** [comment]
I also got a similar problem in both Windows 11 and WSL Ubuntu 22.04 with DLC 3.0 pytorch version. `torch.cuda.is_available()` returned `True`. It appears GPU was engaged during model training but not video analyzing. When I ran `deeplabcut.analyze_videos`, it was really slow and CPU usage was pushed to nearly 100%.

**Comment by roaldarbol** [comment]
@n-poulsen Did you find time to have a look at this? (I can see from the commits that you guys a working hard, so no worries if not, just curious) :-)

**Comment by n-poulsen** [comment]
Hey @roaldarbol - yes currently working on an improvement (should be out soon)! Could you let me know which model architecture you're using?

**Comment by roaldarbol** [comment]
Sound great! I used a ResNet (it says `net_type: resnet_50`).

**Comment by slagathor69** [comment]
For me to utilize my GPU I had to manually edit file:
dlc-models-pytorch/iteration-0/yourexperimentMonthDay-trainset95shuffle1/pytorch_config.yaml

and change 
```
'freeze_bn_stats': true
```
to
```
'freeze_bn_stats': false
```
I also tried setting batch_size in this file and pose_cfg.yaml but found that it had no difference as DeepLabCut reverted back to batch_size of 2 for these processes regardless. 

Even passing  ```torch_kwargs = {'batch_size': 2, 'freeze_bn_stats': False},``` as a parameter to ```deeplabcut.train_network()``` made no difference.
*capital "False" is not error here, it would not accept "false"*

For me what finally ran successfully and utilized the GPU was editing the pytorch_config.yaml file then running
```
deeplabcut.train_network(path_config_file,
                         batch_size = 2,
                         epochs = 1000,
                         save_epochs = 100)
```

Using NVIDIA 4090 with 24GB of VRAM, I couldn't use higher batch_size than 2 here without it running out of VRAM for model hrnet_w48.

**Comment by n-poulsen** [comment]
Hi @roaldarbol! This issue should have been addressed by #2708. You can increase the batch size when analyzing videos, which should boosts inference speed, and increases GPU usage. The default batch size for inference is taken from your project configuration file (there should be a `batch_size` key in there, with a default value of 8), but you can override that by passing the batch size as a parameter to the `analyze_videos` method:

```python
import deeplabcut

deeplabcut.analyze_videos(
    config="/path/to/config.yaml",
    ...,
    batch_size=16,  # batch size for the pose model
    detector_batch_size=8,  # batch size for the detector for top-down models
)
```

**Comment by roaldarbol** [comment]
Sounds great @n-poulsen! I'm not running any tracking at the moment, so I'll just take your word for it. ;-) (And I might drop a line once I get back to it). Good job!

**Comment by frikyng** [comment]
Hi all, 
I am encountering the same issue. Unfortunately though, the remedies suggested haven't worked for me much. My results below are with `batch_size=64, detector_batch_size = 32` in config.yaml and `'freeze_bn_stats': true` in pytorch_config.yaml. 
I have pasted the info I get from the task manager for both the training and inference. 



#### Utilisation during training:
<img width="350" alt="image" src="https://github.com/user-attachments/assets/b6c70030-299b-4890-add7-279ea760c9b9">
<img width="400" alt="image" src="https://github.com/user-attachments/assets/a1a7fc81-d9cb-495b-9d0e-710d51a8d9db">

#### Utilisation during inference:
<img width="350" alt="image" src="https://github.com/user-attachments/assets/ee7b2db2-1afe-4b84-a909-2bc57427afd1">
<img width="400" alt="image" src="https://github.com/user-attachments/assets/28df4d26-ba50-4213-b3fd-7ad850b5124e">


#### My setup for the analysis:
- Windows 10 
- Intel Core i9-14900KS
- Nvidia RTX4090v (24GB)
- DLC 3.0.0rc5
- CUDA toolkit 11.8
- mode: single animal 
- architecture: resnet_50 (pytorch)
- also `torch.cuda.is_available()` does return `true`

**Comment by n-poulsen** [comment]
Hi @frikyng, by low utilization are you speaking about the dedicated GPU memory (2.9 GB and 7.9 GB)? Have you tried changing the batch size and looking at the change in usage?

Your GPUs are clearly being used, so it might just be a question of tuning things.

Are you using the SSDLite detector? As that model is very lightweight, it'll only use a small portion of the GPU.

When it comes to GPU utilization during video inference, updating your project's `config.yaml` file is the way to go - you should have `batch_size: ` and `detector_batch_size: ` parameters in there; those are the values used during video analysis.

**Comment by frikyng** [comment]
Hiya, thanks for the answer. 

Given the documentation I was expecting the GPU RAM to be fully used, and my symptoms looked similar to what was posted earlier, which made me question if I am having a problem. 

I tried setting the batch size and detectorbatch size to high values but this only worked a bit. This increased the GPU utilisation by about 3 times and I also noticed that more CPU cores were engaged like this. I got the best performance at batch_size of 64 (as I have 32 cores) and anything higher would choke the processor, as at 64 already some cores hit 100%. The screenshots I posted are at these best settings. 

About the model you mentioned - I tried to find a detector parameter in config.yaml and pose_cfg.yaml but couldn't see any. Can you tell me how to check what I am using? If you are referring to the net type I am training on it's resnet_50.

**Comment by frikyng** [comment]
This is how the CPU looks when doing an inference run with 'optimal' settings. I could image the CPU is bottlenecking the system here. 

<img width="370" alt="image" src="https://github.com/user-attachments/assets/6f336164-7c93-4e1c-b7f0-b24fdf38c0c2">

**Comment by frikyng** [comment]
Hi @n-poulsen, any updates on this?

**Comment by n-poulsen** [comment]
Hi @frikyng - sorry just getting back to this now. What does your `train_settings` look like in your `pytorch_config.yaml` (and could you maybe share the full contents of the file with me)?

Basically, you want your GPU to be the bottleneck when it comes to training speed (it's the bottleneck if it's being constantly used). However there are other things that take time when training models that happen on the CPU (e.g. loading data & preparing images and targets to give to your model). The `PyTorch` [`DataLoader`](https://pytorch.org/docs/stable/data.html#single-and-multi-process-data-loading) is the worker actually loading the data. If you set `dataloader_workers: 0`, the images will be loaded in the main `CPU` thread, which means `batch_size` images will be loaded sequentially in the main thread before everything is given to the GPU. If you set `dataloader_workers: n` (with `n > 0`), [multi-process data loading](https://pytorch.org/docs/stable/data.html#multi-process-data-loading) which can really speed up training. The "optimal" number to use might vary, but with large batch sizes (32 or 64) I've had 8 or 12 to be the best values for me.

```yaml
train_settings:
  batch_size: 64
  dataloader_workers: 8
```

Again, if you're using very light-weight models (like an `SSDLite` detector), it will be so fast to run that the CPU might be the bottleneck anyways. With other detectors (I'd try the `fasterrcnn_mobilenet_v3_large_fpn`, which is a tad slower but more powerful than the `SSDLite`), the GPU is being used at >80% consistently for me.

Let me know if playing around with the DataLoader workers helps in any way :)

If you're working on an older release, I'd recommend also updating your code to the latest version as there have been many small bug fixes recently.

**Comment by frikyng** [comment]
Hello :) 

First of all I did a full reinstall of DLC3 in a new environment. It's now rc6 instead of rc1. 

I have observed a couple of counterintuitive things. Initially, I tried a couple of configurations for the training with your recommendations. Setting data loader to 8 or 16 does indeed increase the CPU utilisation - thanks for the tip. However, there is no cuda processing when setting this (see screenshot below). You can see in my older posts the cuda processing was active, while it's basically idling now. However(!), I then tried training with dataloaders set to 0 again. Suddenly the GPU memory was used nearly fully and cuda started working Also the training way faster than ever before now. I could also train a resnet_101 network. Do you know what could have happened?

Can you explain what the SSDlite detector is? I cannot find this in any of the settings in the GUI or in the config files. 
On a more general note, are there any important reasons why you would train anything else than a resnet_50 if you're just tracking whisker/paw movements?

Edit - another Q about freeze_bn_stats. I set this to true as from a quick search online it sounded plausible to me.  Also, I saw later that in the documentation it's supposed to always be on. However, I read that on powerful GPUs you can/should keep it on false. What does it do? Any recommendation for my RTX4090?

In any case, I think the issue has fixed itself now. Thanks for the input!

screenshots - both cases have `resnet_50`, `batch_size: 64`,  and `dataloader_pin_memory: true`
**`dataloader_workers: 16`**
config files: [config_files.zip](https://github.com/user-attachments/files/17918989/config_files.zip)
![image](https://github.com/user-attachments/assets/0f7a5c6e-0d3e-43a7-be7f-28d43b1d7214)
**`dataloader_workers: 0`**
config files: [pytorch_config.zip](https://github.com/user-attachments/files/17919228/pytorch_config.zip)
![image](https://github.com/user-attachments/assets/a04b44a0-ee9a-40a6-8dc9-8f05d4bd47ff)

**Comment by nicolin** [comment]
@frikyng  Checking if help is needed from ARC or we can close the service now ticket, from this last message seems that it is a typical windows issue with the driver that we see.

**Comment by frikyng** [comment]
Hi there, I think this is ok now

**Comment by surjeets** [comment]
Hi I am having a similar issue with pytorch where when analyzing videos it only use CPU not GPU and its like 1 it/s
However, **for training GPU is working fine** and I can train a network in less than an hour with the following setting on 4090
Any solution to this? here are the config.yaml and pytorch_config.yaml files

[config.txt](https://github.com/user-attachments/files/18496109/config.txt)
[pytorch_config.txt](https://github.com/user-attachments/files/18496108/pytorch_config.txt)

![Image](https://github.com/user-attachments/assets/a55eead5-5c49-4801-9cdd-c75416afc849)


when I change the following in the config file it starts with ~89 it/s and within few seconds reduces to 1 it/s and only use CPU
batch_size: 32
detector_batch_size: 16

![Image](https://github.com/user-attachments/assets/5967a489-2449-408d-96fd-15ae8f7ee5e4)

![Image](https://github.com/user-attachments/assets/5df82682-104b-4c96-84c5-3b5d258918c0)

With **TensorFlow** (trained network using efficientnet-b0) video evaluation is around 123 it/s. I expect something similar with pytorch but no luck

![Image](https://github.com/user-attachments/assets/28e10e1f-6079-4624-ae28-50080c6230bf)

**Comment by n-poulsen** [comment]
Hey @surjeets! Is the detector inference what's taking a lot of time? The problem might be the one mentioned in issue #2840, which was fixed in #2841. If you update your code (with `pip install --upgrade "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut"` in your conda environment), does that solve the issue and utilize the GPU?

**Comment by surjeets** [comment]
hi @n-poulsen yes its during inference. I just upgraded dlc and now its slower than before. Again no GPU use at all!
I can see that after the upgrade the get_inference_runners is having the changes explained in issue #2840 
I shared the config files earlier do you see anything I could be doing wrong ?
Thanks for your help!

![Image](https://github.com/user-attachments/assets/39f364e0-fc99-4461-926b-be8eb47c74d0)

**Comment by n-poulsen** [comment]
@surjeets If you run `python -c "import torch; print(torch.cuda.is_available())"` in your DeepLabCut environment, does it print `True`?

**Comment by surjeets** [comment]
@n-poulsen Yes that is true. I am sharing the screenshots below. Again the GPU is in use when training the network. I have also edited the config file to have:
**freeze_bn_stats: false
batch_size: 8**

1. GPU is available **YES!**
![Image](https://github.com/user-attachments/assets/67e3c845-378e-4d5a-bee2-ec46ea133624)

2. training dataset has the the following attributes and GPU is in use while training.

![Image](https://github.com/user-attachments/assets/f9243c1d-dbd3-45e4-a2a4-d5473d611caf)

**GPU State while training**

![Image](https://github.com/user-attachments/assets/4a98659b-5885-41db-8447-59f71ae5609d)

**Comment by n-poulsen** [comment]
Thanks @surjeets - could you perhaps run the video analysis using python instead of the GUI? That would help me debug your issue. You can simply run:

```python
(DEEPLABCUT) username> ipython
In [1]: import deeplabcut
In [2]: config = r"C:\path\to\project\config.yaml"
In [3]: videos = [r"C:\path\to\video.mp4"]
In [4]: deeplabcut.analyze_videos(config, videos, shuffle=5, device="cuda", use_shelve=True)
``` 

I set `use_shelve=True` as your video is very long so that ensures you don't run out of memory analyzing it. I also set the device here, let me know if this uses the GPU when running video analysis.

As a side question so I can help you better, did you install DeepLabCut by first cloning the repository or did you directly run `pip install --upgrade "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut"`

**Comment by surjeets** [comment]
Thanks @n-poulsen for the help. It is still slow, not using GPU only CPU. 

![Image](https://github.com/user-attachments/assets/b76b0ba7-5137-49c9-bf50-b5956d417513)

![Image](https://github.com/user-attachments/assets/8da1801a-e4cc-4843-9e41-7c7ac40c6392)

I installed DLC first by cloning the repository and while troubleshooting the problem during video inference I did upgrade to check if it made any difference.

**Comment by n-poulsen** [comment]
If you run with detector batch size 1, does the GPU usage increase?

```python
deeplabcut.analyze_videos(config, videos, shuffle=5, device="cuda", use_shelve=True, detector_batch_size=1)
```

And in your `pytorch_config.yaml`, could you set the `detector/device` key to `cuda`, as shown below:

```yaml
detector:
   ...
  device: cuda
```

**Comment by surjeets** [comment]
same outcome :(
This screen hot has use_shelve=False but I used use_shelve=True as well nothing changes

![Image](https://github.com/user-attachments/assets/852561c3-52bb-41b1-84f3-9e3649d99304)

**Comment by n-poulsen** [comment]
While the object detector is running, could you print the output of the `nvidia-smi` (see [this StackOverflow post](https://stackoverflow.com/questions/57100015/how-do-i-run-nvidia-smi-on-windows) on how to run the command on Windows) so I can see what's happening on your GPU?

**Comment by surjeets** [comment]
@n-poulsen here is the output
I also ran **python -c "import torch; print(torch.version.cuda)"** afterwards to just see if the cuda version shown with nvidi-smi (12.6) and the one I used to compile DLC (11.8) are same. Not sure if that could be the issue? 
I used a different cuda version for a different project.

![Image](https://github.com/user-attachments/assets/384a8619-696d-48c4-bf85-f779175d2735)

**Comment by n-poulsen** [comment]
Thanks @surjeets - perhaps the easiest way to try to fix this issue is through a clean DeepLabCut environment; could you create a new one with the most recent CUDA version so it matches your installation?

```bash
conda create -n deeplabcut3 python=3.10
conda activate deeplabcut3
pip install "numpy<2"
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu126
conda install -c conda-forge pytables==3.8.0
pip install "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut[gui,modelzoo,wandb]"
```

And try running the commands in this new `deeplabcut3` environment

**Comment by frikyng** [comment]
Hi all, I have been getting back to DLC and still wasn't happy with the overall performance of my system even though I thought I fixed it (see above). I have made an interesting observation! 
First of all when installing DLC into a new environment with instructions from [this](https://github.com/DeepLabCut/DeepLabCut/pull/2613) link. However, my GPU wasn't used at all even with the settings I identified above. 

FYI this is the output from nvidia-smi. Ihave CUDA 12.7 installed atm.
![Image](https://github.com/user-attachments/assets/c27d0fe4-dcb3-4dd6-9ec1-5e61dd652514)

Incidentally, I then ran `python -c "import torch; print(torch.version.cuda)"` it returned `false`, i.e. GPU not available! I then asked Claude and he suggested run `conda install pytorch pytorch-cuda=11.8 -c pytorch -c nvidia`, which I did in a fresh environment. After this I indeed got `true` for `python -c "import torch; print(torch.cuda.is_available())"` and the torch version from `python -c "import torch; print(torch.version.cuda)"`. Great news.
I then proceeded with the installation of DLC using `conda install -c conda-forge pytables==3.8.0 ` and `pip install "git+https://github.com/DeepLabCut/DeepLabCut.git@pytorch_dlc#egg=deeplabcut[gui,modelzoo,wandb]"`. This went well, except that at the end of the installation I got an output stating that a torch package got uninstalled. 
I then ran `python -c "import torch; print(torch.cuda.is_available())"` yet again and it returned false!

![Image](https://github.com/user-attachments/assets/a5df3627-9727-4dd1-8430-f0461aea8ebc)

Conclusion - there must be something in the installation that breaks my GPU usage. 

What do you think could cause this behaviour? I was thinking it may be necessary to downgrade my CUDA but Claude said that pytorch-cuda 

EDIT - I just saw the latest comment. I also tried with pytorch-cuda 12.1 but it's the same issue. Also I get that behaviour with the uninstalled torch package. I'll also try these new commands

**Comment by n-poulsen** [comment]
@frikyng it seems the last command you ran (the one for which you shared the logs) uninstalled PyTorch 2.5.1 and installed PyTorch 2.6.0 instead, which means it would no longer be compatible with your GPU... I think it's possible that it did that because `torchvision` wasn't installed (but is needed by DeepLabCut) and it installed the latest `torchvision`. This will likely have installed PyTorch compiled for another CUDA version than 11.8, which is what was installed in your environment.

PyTorch just deprecated `conda` installation (for release 2.6.0 this week), so I updated the installation docs in the pull request #2613 to install it through `pip`.

You should be able to fix your conda environment by running:

```bash
pip uninstall torch torchvision
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118
```

Which will re-install the latest version of `torch` and `torchvision` for CUDA 11.8. But creating a new environment with the commands I shared above should also work.

**Comment by surjeets** [comment]
@n-poulsen This is great! Thank you for your help in fixing this. It was such a silly mistake I should have looked at it earlier. 
All set now!

![Image](https://github.com/user-attachments/assets/b53e47b6-21b5-44d8-8a39-82103f1ff557)

**Comment by n-poulsen** [comment]
@surjeets awesome! glad I could help!

**Comment by frikyng** [comment]
UPDATE 

Wow!! GPU is being used now. All I had to do is run the commands you posted. I see why the error may have come about with the other method I posted. Thanks for the help!

![Image](https://github.com/user-attachments/assets/95c0e204-b333-4122-8b9c-4e725f7895a0)

One more question. In the training log in the console of the iterations in the log there is this message mentioning that you can increase the learning rate depending on the batch size. I suppose this is the one in runner->optimizer->params->lr?
Also, I was wondering if there is a way of seeing the speed of the training similar to the tensorflow version? I just don't know what to expect performance wise and how to tweak my values. 

![Image](https://github.com/user-attachments/assets/93cac75f-ebc7-49f9-9a98-a120a601b1c5)




Lastly, @surjeets I saw earlier that you have an RTX4090 just like me. If I run the prediction with my current settings I get 8.6it/s. I am wondering if you can share your config file for me to compare. Also, what type of network are you using (e.g. resnet_50 or 101)?
Edit2 - with resnet_50 I am getting about 30it/s. So still a bit slower than what you have shown given you'd be evaluating resnet_50

**Comment by n-poulsen** [comment]
@frikyng exactly - generally, you want to increase your learning rate when increasing the batch size. there are some good resources (papers and [StackOverflow posts](https://stackoverflow.com/a/53046624)) on how the learning rate should be scaled. However, note that a larger batch size when training on few images will likely mean you need to train for more epochs (as there will be fewer _iterations_ which update the model parameters). In the example you're training here (with 38 training images and 2 test images), I wouldn't increase the batch size too much.

To get the best possible performance out of your model, it's good to play around with the learning rate and scheduler a bit (you want to start with a larger learning rate, and after some epochs reduce it - choosing how to edit it is described in the [docs (look at the scheduler)](https://deeplabcut.github.io/DeepLabCut/docs/pytorch/pytorch_config.html#runner).

Are you training a single or multi-animal model? And which architecture are you using?

**Comment by frikyng** [comment]
Thanks for the info! I think I'll just set the lr to 0.064 given what is mentioned in the post. 
The small number of frames is due to this just being a test data set. In the real thing I will have many more videos and loads of frames. 

In the final model I will use a single animal model with videos of different animals on a 2-photon setup. My plan is to train resnet_101 since intuitively I'd think it gives more robust results. Though idk how much better the _101 performance is than the _50 model. Are the any other architectures you'd recommend. I am attaching frames from the two angles I will analyse. 

<img width="350" alt="image" src="https://github.com/user-attachments/assets/e9abc3b2-50b3-4aea-b075-bb0cacffa691">
<img width="350" alt="image" src="https://github.com/user-attachments/assets/2f8ed69a-0f0a-4f5e-942e-cabfd794a73a">

**Comment by n-poulsen** [comment]
@frikyng I'd start by trying to train a `resnet_50` and use that as a baseline (then I would train the `resnet_101` and compare results - as it will be slower to analyze videos with, might as well see if it improves performance on the lighter model). I don't have "hard" numbers on this yet, but early results using `cspnext_m` have yielded very good results for me, and it also has the advantage of being faster to run inference with and train than a ResNet.

I think 0.064 might also be a bit too big for the learning rate, and your model might diverge (this would be visible quickly, with the loss "exploding"). I think setting it to 0.001 would be a good place to start

**Comment by frikyng** [comment]
Ok great info. I'll try all these configs. 

One more Q - I tried replicating the results of @surjeets and trained a resnet_50 on my test data set. This was already faster than with the resnet_101 I tried inferencing with before. Then I set the batch_size of the video analysis to 8 and then 16. This actually yielded quite nice results, i.e. 116it/s inference speed ...for both. I also saw that there are 2 CPU cores that are maxed out. This got me thinking if there is a bottle neck (potentially due to data_loader workers?). Interestingly, the same behaviour also seems to be true for @surjeets as his GPU usage seems to run similar a similar job. Also, he has a i9-13900 and I an i9-14900. Do you know what could be holding the GPU back here?

**Comment by frikyng** [comment]
Ok great info. I'll try all these configs. 

One more Q - I tried replicating the results of @surjeets and trained a resnet_50 on my test data set. This was already faster than with the resnet_101 I tried inferencing with before. Then I set the batch_size of the video analysis to 8 and then 16. This actually yielded quite nice results, i.e. 116it/s inference speed ...for both. I also saw that there are 2 CPU cores that are maxed out. This got me thinking if there is a bottle neck (potentially due to data_loader workers?). Interestingly, the same behaviour also seems to be true for @surjeets as his GPU usage seems to run similar a similar job. Also, he has a i9-13900 and I an i9-14900. Do you know what could be holding the GPU back here?

Also, what train results should I target? I am talking about the values from the evaluation (train rmse | train rmse_pcutoff | train mAP | train mAR | test rmse | test rmse_pcutoff | test mAP | test mAR). Upon a quick search I didn't find this in the [documentation](https://deeplabcut.github.io/DeepLabCut/README.html).

**Comment by n-poulsen** [comment]
@frikyng The CPU can indeed become a bottleneck. During training, as we're dealing with images, increasing the number of dataloader_workers can improve GPU utilisation and training speed; so when increasing the batch size, it's also a good idea to increase the number of workers (each worker is in a different thread, so good values to try out are 1, 2, 4, 8, 12 but above that you likely won't get any more speed-up - more info about this [here](https://pytorch.org/docs/stable/data.html#single-and-multi-process-data-loading)).

However, it isn't straightforward to do this during video analysis, as the video needs to be decoded sequentially - so no workers can be used there. Also note that the resolution of your video has a huge impact on FPS, due to the model needing to run on large images but also due to data loading.

When it comes to the results that you should target, there isn't really anything specific; this is because results will be specific to your data. You can't hope for the same performance in a complicated video where many mice overlap than in a video where a single mouse is in an openfield. In the same way, if your image is 2000 pixels by 2000 pixels, an RMSE (root mean square error, or pixel error) of 5px will have a different meaning than if your image is 128 pixels by 128 pixels. It's a good idea to look at the predictions output by the model on a video and make sure they look good; video predictions should also be smooth and not jitter between frames.

A good note [from the docs](https://deeplabcut.github.io/DeepLabCut/docs/maDLC_UserGuide.html#evaluate-the-trained-network) would be:

> What (numerically) comprises an acceptable MAE depends on many factors (including the size of the tracked body parts, the labeling variability, etc.). Note that the test error can also be larger than the training error due to human variability (in labeling, see Figure 2 in Mathis et al, Nature Neuroscience 2018).

If we look at [figure 2](https://www.nature.com/articles/s41593-018-0209-y/figures/2), the human variability sits just below 3 pixels, and the model error can actually go below that value; with the examples you shared, I'd expect the RMSE to go below 10 pixels (and likely below 5). I'd also expect your mAP to be above 90, but for single animal datasets RMSE is a good metric to look at.

The other metrics, mAP and mAR, are more useful for multi-animal dataset. There's detailed information on [computing mAP for keypoints](https://cocodataset.org/#keypoints-eval), but it's similar to computing mAP for bounding boxes for which there are more ["visual" resources to understand the metric](https://www.v7labs.com/blog/mean-average-precision).

**Comment by surjeets** [comment]
@frikyng here is the config file adding it as txt and I removed path information that you can add that is relevant to you project
[config.txt](https://github.com/user-attachments/files/18606591/config.txt)

**Comment by frikyng** [comment]
Ok nice. This is some really good info. Time to get to training. Thanks very much @n-poulsen!
Also thanks for the file @surjeets!
