### ISSUE TITLE
GPU not being used

### ISSUE THREAD

**Issue by ArranReader** [DeepLabCut/DeepLabCut#3068]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating System

Windows 11

### DeepLabCut version

3.0.0rc8

### What engine are you using?

pytorch

### DeepLabCut mode

single animal

### Device type

GeForce RTX 3060

<img width="734" height="325" alt="Image" src="https://github.com/user-attachments/assets/29d39956-90cd-467a-b0b6-63b60b2b6e58" />

### Bug description 🐛

I have followed installation instructions but I am unable to train network using my GPU. Training runs without errors but CPU is being used instead. I am hoping I have not missed anything regarding compatibility between driver, CUDA, and Pytorch. I am using the GUI.

I have the latest version of Pytorch (2.7.1) for CUDA 12.8 and torch.cuda.is_available() returns True.

I have tried uninstalling and reinstalling Pytorch as suggested [here](https://github.com/DeepLabCut/DeepLabCut/issues/2998).

Please could you advise?

<img width="936" height="670" alt="Image" src="https://github.com/user-attachments/assets/6b9dcc19-336a-4a83-a15b-3baddd542fef" />

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by programerkotik** [comment]
I encountered the same issue on Linux (Ubuntu) using PyTorch 2.7.1 with CUDA 12.6.

I was running `deeplabcut.create_pretrained_project()` to use a pretrained model from the model zoo. Since this function doesn’t expose a `device `parameter, I looked into the source code and found where `analyze_video` is called. I added `device='cuda' ` there manually, and now it works correctly!

**Comment by ArranReader** [comment]
Many thanks for this suggestion @programerkotik - I ended up manually editing `pytorch_config` to change `device: auto` to `device: 'cuda'`. This seems to have revealed the source of the problem, as trying to train with this setting elicited the following error:

`AssertionError: Torch not compiled with CUDA enabled`

This led me to realise that I had erroneously installed pytorch in conda rather than the DeepLabCut environment.
