### ISSUE TITLE
error when training the network :Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure

### ISSUE THREAD

**Issue by tochenan** [DeepLabCut/DeepLabCut#354]
Hello developer,
When I was training the neural network I met the following error:
2019-07-07 16:35:58.403047: E tensorflow/stream_executor/cuda/cuda_event.cc:48] Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure
2019-07-07 16:35:58.403049: E tensorflow/stream_executor/cuda/cuda_driver.cc:1011] could not synchronize on CUDA context: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure ::
2019-07-07 16:35:58.422214: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:274] Unexpected Event status: 1

As I am not really familiar with CUDA driver, I am really confused about what I can do to fix the problem.

**Desktop (please complete the following information about your system):**
 - Window 10
 - DeepLabCut Version  ('2.0.7.1')
- CUDA version: nvcc:
 NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:11:20_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.168
 - Browser [chrome]

Thank you very much.

**Comment by MMathisLab** [comment]
please check your GPU card driver; there needs to be a correct match between the GPU, CUDA, and the tensorflow version. 

https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md#troubleshooting

**Comment by tochenan** [comment]
so I check the version of the GPU, CUDA and tensorflow version,
I have both NVIDIA Quadro M4000 and NVIDIA Quadro P2000 

I use NVIDIA CUDA 10.1, tensorflow-gpu 1.13.1 and NVIDIA driver 431.02 version
I can't find the information related to the compatible driver of NVIDIA CUDA 10.1 for windows but I followed the guide on the website https://class.hujiang.com/lesson/p3_10584900/try

Do I need to reinstall my driver to a lower version followed in this website in order to make sure that everything is working? https://github.com/AlexEMG/DeepLabCut/blob/master/docs/installation.md#troubleshooting

**Comment by MMathisLab** [comment]
Since this is not a DeepLabCut code issue, I will close it. I cannot help troubleshoot for tensorflow and CUDA, but please search stack overflow and other issues for assistance. It's likely your driver is incorrect for your GPU card. NVIDIA gives an extensive list to look at: https://www.nvidia.com/Download/index.aspx

**Comment by jgmeyerucsd** [comment]
Had this error and wanted to share with others what worked for me because I spent days troubleshooting. 

Seems like a mismatch between the CUDA TOOLKIT and the GPU driver. 

I have GTX 1080 cards, and CUDA TOOLKIT 10.1 with driver version 426.00 is the only combination that doesn't give me the error. This is probably different on a GPU specific basis unfortunately. i suggest just trying many different driver versions.

**Comment by yuanhzha** [comment]
Could anyone answer my question at: https://stackoverflow.com/questions/65067397/error-polling-for-event-status-failed-to-query-event-cuda-error-launch-failed
