### ISSUE TITLE
Index Error on Step 1 EvaluateModelonDataset.py (tuple index out of range)

### ISSUE THREAD

**Issue by p-khosla** [DeepLabCut/DeepLabCut#42]
**Describe the problem**
When running step1.evaluatemodelondataset.py the following error occurs.

Starting evaluation
Running  DeepCut_resnet_50_95shuffle1_400000forTask_movement  with # of trainingiterations: 400000
WARNING:tensorflow:From /home/dave/DeepLabCut/pose-tensorflow/nnet/pose_net.py:52: calling resnet_arg_scope (from tensorflow.contrib.slim.python.slim.nets.resnet_utils) with is_training is deprecated and will be removed after 2017-08-01.
Instructions for updating:
Pass is_training directly to the network instead of the arg_scope.
WARNING:tensorflow:From /home/dave/DeepLabCut/pose-tensorflow/nnet/pose_net.py:52: calling resnet_arg_scope (from tensorflow.contrib.slim.python.slim.nets.resnet_utils) with is_training is deprecated and will be removed after 2017-08-01.
Instructions for updating:
Pass is_training directly to the network instead of the arg_scope.
2018-08-14 17:27:04.116584: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_UNKNOWN
2018-08-14 17:27:04.116624: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: 00e5be448947
2018-08-14 17:27:04.116636: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: 00e5be448947
2018-08-14 17:27:04.116688: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 384.130.0
2018-08-14 17:27:04.116722: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.130  Wed Mar 21 03:37:26 PDT 2018
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 
"""
2018-08-14 17:27:04.116749: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 384.130.0
2018-08-14 17:27:04.116764: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 384.130.0
Analyzing data...
0it [00:00, ?it/s]

Traceback (most recent call last):
  File "EvaluateNetwork.py", line 89, in <module>
    Data = pd.read_hdf(os.path.join("Results",DLCscorer + '.h5'),'df_with_missing')
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/pytables.py", line 371, in read_hdf
    'File %s does not exist' % path_or_buf)
FileNotFoundError: File Results/DeepCut_resnet_50_95shuffle1_400000forTask_movement.h5 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "EvaluateNetwork.py", line 115, in <module>
    pose = predict.argmax_pose_predict(scmap, locref, cfg.stride)
  File "/home/dave/DeepLabCut/pose-tensorflow/nnet/predict.py", line 43, in argmax_pose_predict
    num_joints = scmap.shape[2]
IndexError: tuple index out of range
root@00e5be448947:/home/dave/DeepLabCut/Evaluation-Tools# 

**To Reproduce**
Simply run Step 1 for the error to occur.

**Additional context**
This is our first training set with the software, we successfully trained for 400000 iterations and then attempted to evaluate the program.

**Comment by meet10may** [comment]
Could you please share **your** ```pose_cfg.yaml``` file. We particularly wonder how many body parts you are tracking?

**Comment by p-khosla** [comment]
Can't share the actual file, but here's the code in it.

```
dataset: willbeautomaticallyupdatedbyStep3code
num_joints: willbeautomaticallyupdatedbyStep3code
all_joints: willbeautomaticallyupdatedbyStep3code
all_joints_names: willbeautomaticallyupdatedbyStep3code

# Hyperparameters below worked well for our tasks:

# all locations within this distance threshold are considered
# positive training samples for detector
pos_dist_thresh: 17

# all images in the dataset will be rescaled by the following
# scaling factor to be processed by the CNN. You can select the
# optimal scale by cross-validation
global_scale: 0.8
# During training an image will be randomly scaled within the
# range [scale_jitter_lo; scale_jitter_up] to augment training data,
scale_jitter_lo: 0.5
scale_jitter_up: 1.5
# Randomly flips an image horizontally to augment training data
mirror: false

# Type of the CNN to use, currently resnet_101 and resnet_50
# are supported
net_type: resnet_50
init_weights: ../../pretrained/resnet_v1_50.ckpt
#init_weights: ./snapshot-5000


# Location refinement parameters (check https://arxiv.org/abs/1511.06645)
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801

# Enabling this adds additional loss layer in the middle of the ConvNet,
# which helps accuracy.
intermediate_supervision: false
intermediate_supervision_layer: 12

# all images larger with size
# width * height > max_input_size*max_input_size are not used in training.
# Prevents training from crashing with out of memory exception for very
# large images.
max_input_size: 1000

# Learning rate schedule for the SGD optimiser. 
multi_step:
- [0.005, 10000]
- [0.02, 430000]
- [0.002, 730000]
- [0.001, 1030000]

# How often display loss
display_iters: 1000
# How often to save training snapshot
save_iters: 50000
```
We are tracking two body parts - the nose and the tail

**Comment by AlexEMG** [comment]
In that case I have never seen this problem before -- and it is hard to find out what is happening _in lieu of more information._ I would check if a) snapshot is found and loaded correctly b) analyze ```scmap``` does it have n x m x 2 dimensions (as 2 body parts suggest?. Then why can the 3rd dimension not be accessed?

**Comment by p-khosla** [comment]
My apologies, the issue was with our labeling where we labeled two parts, but only inputted one into the myconfig file. Relabeling our data properly fixed the issue.

**Comment by sirinire** [comment]
I am running into this exact same error message: 
```
(dlcdependencies) E:\Github\DeepLabCut\Evaluation-Tools>python Step1_EvaluateModelonDataset.py
Running  DeepCut_resnet_50_90shuffle1_750000forTask_Stimulus pole  with # of trainingiterations: 750000
Starting evaluation
Running  DeepCut_resnet_50_90shuffle1_750000forTask_Stimulus pole  with # of trainingiterations: 750000
2018-09-05 11:18:18.893283: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-09-05 11:18:19.226923: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1356] Found device 0 with properties:
name: Quadro P4000 major: 6 minor: 1 memoryClockRate(GHz): 1.48
pciBusID: 0000:73:00.0
totalMemory: 8.00GiB freeMemory: 6.63GiB
2018-09-05 11:18:19.236713: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1435] Adding visible gpu devices: 0
2018-09-05 11:18:19.878598: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-05 11:18:19.883702: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:929]      0
2018-09-05 11:18:19.886189: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:942] 0:   N
2018-09-05 11:18:19.888829: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6407 MB memory) -> physical GPU (device: 0, name: Quadro P4000, pci bus id: 0000:73:00.0, compute capability: 6.1)
Analyzing data...
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "EvaluateNetwork.py", line 89, in <module>
    Data = pd.read_hdf(os.path.join("Results",DLCscorer + '.h5'),'df_with_missing')
  File "C:\Users\Nuo\Anaconda3\envs\dlcdependencies\lib\site-packages\pandas\io\pytables.py", line 371, in read_hdf
    'File %s does not exist' % path_or_buf)
FileNotFoundError: File Results\DeepCut_resnet_50_90shuffle1_750000forTask_Stimulus pole.h5 does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "EvaluateNetwork.py", line 115, in <module>
    pose = predict.argmax_pose_predict(scmap, locref, cfg.stride)
  File "E:\Github\DeepLabCut\pose-tensorflow\nnet\predict.py", line 43, in argmax_pose_predict
    num_joints = scmap.shape[2]
IndexError: tuple index out of range

```

I am using only one body part and in some frames the body part was occluded entirely, so I emitted labels from those frames using "invisible boundary" in myconfig.

**Comment by AlexEMG** [comment]
I will commit a version that allows to have exactly 1 bodypart soon (a rather rare case). I will post here if that was done.

**Comment by AlexEMG** [comment]
I just fixed this - also see issue: https://github.com/AlexEMG/DeepLabCut/issues/66
