### ISSUE TITLE
Running Deeplabcut, but there is no change in GPU usage.

### ISSUE THREAD

**Issue by DotchGNU** [DeepLabCut/DeepLabCut#450]
**Your Operating system and DeepLabCut version**
Window 10 professional, with an Anaconda Env, & DeepLabCut 2.0.8

Please complete the following information about your system:
OS: Windows 10
DeepLabCut Version 2.0.8
Browser : chrome

**Describe the problem**

Running Deeplabcut, but there is no change in GPU usage.

(Actually, I'm new to use tensorflow, and this is the first time to use GPU myself. So there would be a lot of clumsy points.)

1) when I call `dlc.train_network(path_config_file`(dlc=deeplabcut), it shows "Starting training...." message 

2) But I have run the program for few days, there do not print iteration information. (although computer is still running well)

* a day after running the program
![image3](https://user-images.githubusercontent.com/55175229/66466029-f2d04f00-eabc-11e9-949e-df7605ba308b.png)

3) So I check the `nvidia-smi` and control panel of window. (image below) 

**Screenshots**
* `nvidia-smi` while running deeplabcut
![image1](https://user-images.githubusercontent.com/55175229/66465865-a127c480-eabc-11e9-91cd-9d00b2ce22a3.png)

* control panel of window while running deeplabcut 
![image2](https://user-images.githubusercontent.com/55175229/66465902-b43a9480-eabc-11e9-9cc5-d3c48ffece77.png)

**Additional context**

I think the GPU is not utilized while deeplabcut is running. The video file I used for analysis is low-quality .mp4 file, and I just add 4 point for analysis. How can I solve this problem?

**Comment by DotchGNU** [comment]
In addition, when I run `dlc.train_network`, I get the following error message: 
![image4](https://user-images.githubusercontent.com/55175229/66489611-dcd98300-eaea-11e9-96ff-49babf38660e.PNG)

Regardless of the error message, the message `starting training ...` is displayed and I thought there was no problem. but now I think this problem may be the cause. 

Last time I ran deeplabcut, iteration information was displayed without this message, but I don't know why it doesn't work this time.

I am the undergraduate student in biology major... maybe it would be tiny problem but I don't have an idea to solve this problem. Please give me a hand. thanks a lot!

**Comment by MMathisLab** [comment]
any updates, @DotchGNU?

**Comment by DotchGNU** [comment]
Oh! thanks for your reply. I'm pretty new to github, so confusing the forum and Issues. I'm gonna move this question to forum. 
By the way, the problem is that I modified several lines in `pose_cfg.yaml` file which you mentioned never modifying : ` num_joints`. I supposed that it makes invalid matrix  while the dlc running. 
So I fix it, and now it works!! 

Of note, in Window, "NVIDIA_smi" reports quite wrong information. I think it's because of version problem. So when I wank to check GPU usage, I use Window Task Maneger panels as described for this website : https://www.howtogeek.com/351073/how-to-monitor-gpu-usage-in-the-windows-task-manager/.

P.S. Without this program, my experimental analysis would have been very difficult.  I really appreciate to you.
